version: '3'
services:
  express-server:
    container_name: express
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SALT=10
      - PORT=4200
      - BASE_URL=/api
      - JWT_SECRET=test
      - MONGO_LOGIN=admin
      - MONGO_PASSWORD=admin
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_AUTH_DB=admin
    ports:
      - 4200:4200
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5