version: '3'
services:
  express-server:
    container_name: express
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    expose:
      - 4200
    depends_on:
      - mongo-db
  front-server:
    container_name: front
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - express-server
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5