version: '3'
services:
  express-server:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200-4204:4200"
    deploy:
      replicas: 5
    depends_on:
      - mongo-db
    networks:
      - app-net
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5
    networks:
      - app-net
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: my-nginx
    depends_on:
      - express-server
    ports:
      - "8000:8000"
      - "443:443"
    networks:
      - app-net
networks:
    app-net:
      driver: bridge
